Resolucion Ejercicio libreria
WaldoGaspari/aydoo-2018 pull request #3
Opened 2018-04-25 02:28 UTC by WaldoGaspari

2018-04-29 10:54 UTC, anero requested changes

2018-04-29 10:54 UTC, anero commented on ejercicio_libreria/src/main/java/ar/edu/untref/aydoo/ArticuloDeLibreria.java
> +		this.cambiarPrecio(this.obtenerPrecio() + calcularIVA(precio));
sería más correcto aplicar el IVA antes de llamar a `super` en vez de exponer un método `cambiarPrecio` solo para modelar este caso.

2018-04-29 10:54 UTC, anero commented on ejercicio_libreria/src/main/java/ar/edu/untref/aydoo/Cliente.java
> +		return this.comprasRealizadas;
al devolver una referencia a la lista de compras estás rompiendo el encapsulamiento (cualquiera puede modificarla sin necesidad de usar `agregarCompra`). El método debería devolver una interfaz que solo permita recorrer la colección sin modificarla, o una replica de la colección que si es modificada desde afuera de la clase no afecta el valor del atributo del objeto `Cliente`

2018-04-29 10:54 UTC, anero commented on ejercicio_libreria/src/main/java/ar/edu/untref/aydoo/Cliente.java
> +		return this.suscripcionesAdheridas;
mismo comentario sobre la ruptura del encapsulamiento

2018-04-29 10:54 UTC, anero commented on ejercicio_libreria/src/main/java/ar/edu/untref/aydoo/Compra.java
> +	private Mes mes;
no cumple la consigna: como no se incluye el año el modelo solamente funciona para el primer año.

2018-04-29 10:54 UTC, anero commented on ejercicio_libreria/src/main/java/ar/edu/untref/aydoo/Compra.java
> +		return this.productos;
mismo comentario sobre el encapsulamiento que te hice en la clase `Cliente`

2018-04-29 10:54 UTC, anero commented on ejercicio_libreria/src/main/java/ar/edu/untref/aydoo/Compra.java
> +		if (this.productos.isEmpty()) {
no es necesario manejar el caso de que la lista de compras este vacía por separado: si es así el iterador va a devolver `false` al llamar a `hasNext()` la primera vez

2018-04-29 10:54 UTC, anero commented on ejercicio_libreria/src/main/java/ar/edu/untref/aydoo/Libreria.java
> +					if (this.clientes.contains(cliente) && !saberSiElClientePoseeUnaSuscripcionAnual(cliente)) {
no cumple la consigna: el 5% de descuento para clientes registrados **no se aplica solo** para las compras de productos con suscripción. ej: Un cliente registrado con una suscripción a una revista **debería recibir un 5% de descuento si compra un libro**

2018-04-29 10:54 UTC, anero commented on ejercicio_libreria/src/test/java/ar/edu/untref/aydoo/CompraTest.java
> +	public void unaCompraDeTresProductosDeberiaDevolverme120() {
el nombre del test debería ser claro en cuanto a cual es el escenario (no es necesario tanto detalle de cuál es exactamente el valor esperado, sino porque se espera ese valor). ej: un nombre mejor para este test sería `obtenerTotalDeLaCompraDeProductosSinIvaDeberíaDevolverSumaDePrecios`

2018-05-01 19:27 UTC, WaldoGaspari commented on ejercicio_libreria/src/main/java/ar/edu/untref/aydoo/ArticuloDeLibreria.java
> +		this.cambiarPrecio(this.obtenerPrecio() + calcularIVA(precio));
Diego, de todas las correcciones esta es la única que no logro poder hacer. Cuando quiero hacer lo que me pedís, en el constructor no me deja; me tira que la primera linea dentro del constructor debe ser super(). Si tu corrección va por otro lado no me doy cuenta qué tendría que modificar. Si podrías darme una mano con eso joya así ya lo re-entrego. Gracias.

2018-05-01 19:30 UTC, WaldoGaspari commented on ejercicio_libreria/src/main/java/ar/edu/untref/aydoo/Libreria.java
> +					if (this.clientes.contains(cliente) && !saberSiElClientePoseeUnaSuscripcionAnual(cliente)) {
En esta corrección, no me doy cuenta que estaría mal... El método calcula el descuento del 5% a todas las compras de los  clientes registrados menos cuando el cliente tiene una suscripción anual ya que solo le corresponde el descuento del 20%, pero solo para esa compra. Si el cliente tiene otras compras si le calcula el 5%. Esta bien lo que entiendo del problema o vos te referis a otra cosa? Gracias.

2018-05-01 19:35 UTC, anero commented on ejercicio_libreria/src/main/java/ar/edu/untref/aydoo/ArticuloDeLibreria.java
> +		this.cambiarPrecio(this.obtenerPrecio() + calcularIVA(precio));
En vez de pasarle a super la variable `precio` directamente, podrías pasarle el resultado de calcular el precio con el IVA (ej: `super(calcularPrecioConIva(precio))`)

2018-05-01 19:42 UTC, WaldoGaspari commented on ejercicio_libreria/src/main/java/ar/edu/untref/aydoo/ArticuloDeLibreria.java
> +		this.cambiarPrecio(this.obtenerPrecio() + calcularIVA(precio));
Perfecto, ahora entiendo. Gracias Diego

2018-05-01 19:44 UTC, anero commented on ejercicio_libreria/src/main/java/ar/edu/untref/aydoo/Libreria.java
> +					if (this.clientes.contains(cliente) && !saberSiElClientePoseeUnaSuscripcionAnual(cliente)) {
El tema es que en `saberSiElClientePoseeUnaSuscripcionAnual` no estas verificando que la compra que estas procesando en ese momento haya sido sobre el producto para el que tiene la suscripción. Entonces por ejemplo si el cliente está registrado y compra 2 revistas, una con suscripción anual y otra no, no le vas a hacer el descuento del 5% sobre la compra de la revista *sin* suscripción anual.

2018-05-01 21:24 UTC, WaldoGaspari commented on ejercicio_libreria/src/main/java/ar/edu/untref/aydoo/Libreria.java
> +					if (this.clientes.contains(cliente) && !saberSiElClientePoseeUnaSuscripcionAnual(cliente)) {
Ok, entiendo ahora. Ya hice todas las modificaciones solicitadas Diego. Espero que haya comprendido. Gracias por todo

2018-05-05 22:29 UTC, anero approved these changes

2018-05-05 22:29 UTC, anero commented on ejercicio_libreria/src/main/java/ar/edu/untref/aydoo/Cliente.java
> +		return comprasRealizadas;
Ojo que acá seguís devolviendo una referencia al atributo `comprasRealizadas`. La variable que estás declarando es básicamente un "puntero" al objeto. Para evitar romper el encapsulamiento en vez de devolver `List<Compra>` podrías devolver `Iterable<Compra>`, esta interfaz te permite recorrer las compras sin posibilidad de agregar o eliminar elementos de la colección.

2018-05-06 23:09 UTC, merged