Resolucion Ejercicio Fibo3
WaldoGaspari/aydoo-2018 pull request #4
Opened 2018-04-30 23:54 UTC by WaldoGaspari

2018-05-06 22:19 UTC, anero requested changes

2018-05-06 22:19 UTC, anero commented on Fibo3/src/main/java/ar/edu/untref/aydoo/Program.java
> +}
Esta clase tiene demasiadas responsabilidades y esta implementada de forma procedural, no orientada a objetos

2018-05-06 22:19 UTC, anero commented on Fibo3/src/main/java/ar/edu/untref/aydoo/Program.java
> +	    direccion = formato.charAt(4);
No es correcto asumir posiciones estáticas de los argumentos: los comandos de Fibo1 (ej: `java -jar fibo.jar 8`) deberían seguir andando. 
Además las opciones `-o`, `-f` y `-m` pueden darse en cualquier orden, o sea:

`java -jar fibo.jar -o=vd -f=salida.txt -m=l 5`
`java -jar fibo.jar  -m=l -o=vd -f=salida.txt 5`
`java -jar fibo.jar   -f=salida.txt -m=l -o=vd 5`

son todos equivalentes.

2018-05-06 22:19 UTC, anero commented on Fibo3/src/main/java/ar/edu/untref/aydoo/SerieFibonacci.java
> +	public static int calcularSerieDeFibonacci(int numero) {
Este método no esta calculando la serie sino solamente uno de sus elementos. El nombre tiene que ser correcto y claro

2018-05-06 22:19 UTC, anero commented on Fibo3/src/test/java/ar/edu/untref/aydoo/FiboTest.java
> +	}
¿Por qué elegiste estos números? ¿Usaste algún criterio para elegir que tests crear o elegiste números al azar para "validar" que el objeto hace lo que tiene que hacer? 
Si es el 2do caso, no tiene sentido que pongas 2, 5 o 2000 tests porque nada te asegura que para el test 2001 no va a fallar. Tenés que elegir casos que cubran los extremos (ej: 0, 1), las excepciones (ej: -1) y un caso concreto

2018-05-08 02:05 UTC, WaldoGaspari commented on Fibo3/src/main/java/ar/edu/untref/aydoo/Program.java
> +	    direccion = formato.charAt(4);
Diego, no sabia que se podía dar en cualquier orden... sin embargo, no puedo darme cuenta como hacer eso. O sea, cómo analizar, sin importar el orden, los parámetros para que el programa haga lo que tiene que hacer, Si podrías darme una mano con eso así puedo seguir. Gracias.

2018-05-08 02:17 UTC, anero commented on Fibo3/src/main/java/ar/edu/untref/aydoo/Program.java
> +	    direccion = formato.charAt(4);
Waldo, la idea es que agarres cada parámetro y en base al tipo (`-o`, `-m` o `-f`) establezcas cual es el comportamiento del programa. Es cuestión de ver como comienza cada elemento del array `arg` y en base a eso lo parsees como corresponda...

2018-05-11 02:25 UTC, anero approved these changes

2018-05-12 16:50 UTC, merged